[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.git          # root of the project
    | \.venv
  )/
)
'''


[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 88

[tool.pylint.messages_control]
# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifiers separated by comma (,) or put this
# option multiple times (only on the command line, not in the configuration
# file where it should appear only once). You can also use "--disable=all" to
# disable everything first and then reenable specific checks. For example, if
# you want to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable = [
    # black
    'bad-continuation',
    'bad-whitespace',
    # flake8
    'missing-docstring',
    'syntax-error',
    'line-too-long',
    'trailing-whitespace',
    'missing-final-newline',
    'trailing-newlines',
    'bad-indentation',
    'unused-import',
    'wildcard-import',
    'unused-wildcard-import',
    'unused-variable',
    # project
    'duplicate-code',
    'no-else-return',
    'invalid-name',
    'no-else-continue',
]
